#!/usr/bin/env python3

from collections import defaultdict

example_input = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

def count_splits(inp):
    lines = inp.splitlines()
    beams = defaultdict(int)
    beams[lines[0].index('S')]  = 1
    for line in lines[1:]:
        nxt = defaultdict(int)
        for b in beams:
            if line[b] == '^':
                if b-1 >= 0:
                    nxt[b-1] += beams[b]
                if b+1 < len(line):
                    nxt[b+1] += beams[b]
            else:
                nxt[b] += beams[b]
        if nxt:
            beams = nxt
    return sum(beams.values())
assert (got := count_splits(example_input)) == 40, got

print(count_splits(open('inputs/day07.input.txt').read()))
