#!/usr/bin/env python3

example_input = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

def count_splits(inp):
    lines = inp.splitlines()
    beams = set([lines[0].index('S')])
    nsplits = 0
    for line in lines[1:]:
        nxt = set()
        for b in beams:
            if line[b] == '^':
                if b-1 >= 0:
                    nxt.add(b-1)
                if b+1 < len(line):
                    nxt.add(b+1)
                nsplits += 1
            else:
                nxt.add(b)
        if nxt:
            beams = nxt
        print(f'nsplit={nsplits} len(beams)={len(beams)}')
    return nsplits
assert (got := count_splits(example_input)) == 21, got

print(count_splits(open('inputs/day07.input.txt').read()))
